version: "3.7"
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["python", "app.py", "--host", "0.0.0.0"]

networks:
  default:
    driver: bridge
